name: Upload Code to S3 on New Tag

on:
  push:
    tags:
      - '*'  # Trigger on any tag creation

jobs:
  upload_to_s3:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli -y

      - name: Zip repository code
        run: zip -r code.zip .

      - name: Upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          TAG_NAME=$(echo "${GITHUB_REF#refs/tags/}")
          echo "Current TAG_NAME: $TAG_NAME"
          if ! aws s3 cp code.zip s3://crego-jupiter-web/$TAG_NAME/code.zip --debug; then
              echo "AWS CLI command failed"
              exit 1
          fi
