name: Upload Code to S3 on New Tag

on:
  push:
    tags:
      - '*'  # Trigger on any tag creation

jobs:
  upload_to_s3:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install AWS CLI in the GitHub Actions runner
      - name: Install AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install awscli -y

      # Zip the code in the repository
      - name: Zip repository code
        run: zip -r code.zip .

      # Upload the zipped code to S3
      - name: Upload to S3
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  run: |
    TAG_NAME=$(echo "${GITHUB_REF#refs/tags/}")  # Get the current tag name
    aws s3 cp code.zip s3://crego-jupiter-web/$TAG_NAME/code.zip
